import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import { z } from 'zod'
import { db } from '@/lib/db'
import { users, companies } from '@/lib/schema'
import { eq } from 'drizzle-orm'
import { purchaseVapiNativeNumber, getPhoneNumberById, deletePhoneNumber, registerTwilioNumber, VapiError } from '@/lib/vapi'
import { purchaseNumber, TwilioError } from '@/lib/twilio'

const Schema = z.object({
  // Vapi-native: placeholder `__vapi__:<COUNTRY>:<AREA_CODE>` generated by client
  // Twilio: real E.164 phone number e.g. +14155551234
  phone_number: z.string().min(1),
  provider: z.enum(['vapi', 'twilio']).default('vapi'),
})

export async function POST(req: Request) {
  const supabase = createClient()
  const { data: { user: _authUser } } = await supabase.auth.getUser()
  if (!_authUser) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const dbUser = await db.query.users.findFirst({ where: eq(users.clerk_id, _authUser.id) })
  if (!dbUser?.company_id) return NextResponse.json({ error: 'Company not found' }, { status: 404 })

  const body = await req.json()
  const parsed = Schema.safeParse(body)
  if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 })

  const company = await db.query.companies.findFirst({ where: eq(companies.id, dbUser.company_id) })
  if (!company) return NextResponse.json({ error: 'Company not found' }, { status: 404 })

  if (company.vapi_phone_number) {
    return NextResponse.json(
      { error: 'Your account already has a phone number. Release the current number first.' },
      { status: 409 },
    )
  }

  if (!company.vapi_assistant_id || company.vapi_assistant_id === 'null') {
    return NextResponse.json(
      { error: 'AI assistant must be configured before purchasing a phone number.' },
      { status: 422 },
    )
  }

  const { phone_number, provider } = parsed.data
  const numberName = `${company.name} Main Line`

  // ── Path A: Vapi-native ────────────────────────────────────────────────────
  // The client sends a placeholder `__vapi__:<COUNTRY>:<AREA_CODE>`.
  // Vapi provisions the real number and returns it in the response.
  if (provider === 'vapi') {
    const isVapiPlaceholder = phone_number.startsWith('__vapi__')
    const [, , areaCode] = isVapiPlaceholder ? phone_number.split(':') : []
    try {
      const vapiNumber = await purchaseVapiNativeNumber({
        numberDesiredAreaCode: areaCode || undefined,
        name: numberName,
        assistantId: company.vapi_assistant_id,
      })

      // Vapi provisions numbers asynchronously — the `number` field may be null
      // in the creation response. Poll GET /phone-number/{id} until it appears.
      let actualNumber = vapiNumber.number ?? vapiNumber.phoneNumber
      if (!actualNumber && vapiNumber.id) {
        for (let i = 0; i < 6; i++) {
          await new Promise((r) => setTimeout(r, 2000))
          const fetched = await getPhoneNumberById(vapiNumber.id)
          actualNumber = fetched.number ?? fetched.phoneNumber
          if (actualNumber) break
        }
      }

      // If still no number after polling, clean up the orphaned Vapi record
      if (!actualNumber) {
        if (vapiNumber.id) {
          try { await deletePhoneNumber(vapiNumber.id) } catch { /* best effort cleanup */ }
        }
        throw new Error(
          'Vapi could not provision a phone number. This is usually caused by insufficient Vapi account balance. ' +
          'Please top up your Vapi account at dashboard.vapi.ai → Billing, then try again.',
        )
      }

      await db.update(companies)
        .set({ vapi_phone_number: actualNumber, vapi_phone_number_id: vapiNumber.id })
        .where(eq(companies.id, dbUser.company_id))

      return NextResponse.json({ success: true, phone_number: actualNumber, provider: 'vapi' })
    } catch (err) {
      console.error('[api/vapi/numbers/purchase] Vapi purchase failed:', err)
      if (isVapiPlaceholder) {
        // Placeholder numbers cannot fall back to Twilio — surface the real error
        const msg = err instanceof Error ? err.message : 'Failed to provision number via Vapi.'
        return NextResponse.json({ error: msg }, { status: 502 })
      }
      // Real E.164 number via Vapi failed → fall through to Twilio
    }
  }

  // ── Path B: Twilio (BYO or fallback) ──────────────────────────────────────
  let purchased
  try {
    purchased = await purchaseNumber(phone_number)
  } catch (err) {
    console.error('[api/vapi/numbers/purchase] Twilio purchase failed:', err)
    if (err instanceof TwilioError) {
      if (err.code === 'not_configured') {
        return NextResponse.json(
          { error: 'Phone number purchasing is not available. Please contact support.' },
          { status: 503 },
        )
      }
      return NextResponse.json({ error: err.message || 'Failed to purchase phone number.' }, { status: 502 })
    }
    return NextResponse.json({ error: 'Failed to purchase phone number. Please try again.' }, { status: 500 })
  }

  // Register the Twilio number with Vapi
  const serverUrl = `${process.env.N8N_WEBHOOK_BASE_URL}/webhook/vapi/inbound`
  let vapiNumber
  try {
    vapiNumber = await registerTwilioNumber({
      number: purchased.phone_number,
      name: numberName,
      assistantId: company.vapi_assistant_id,
      serverUrl,
    })
  } catch (err) {
    console.error('[api/vapi/numbers/purchase] Vapi registration failed:', err)
    await db.update(companies)
      .set({ vapi_phone_number: purchased.phone_number, vapi_phone_number_id: null })
      .where(eq(companies.id, dbUser.company_id))
    return NextResponse.json({
      success: true,
      phone_number: purchased.phone_number,
      provider: 'twilio',
      warning: err instanceof VapiError
        ? 'Number purchased but AI assistant connection failed. Please contact support.'
        : 'Number purchased but AI setup incomplete. Please contact support.',
    })
  }

  await db.update(companies)
    .set({ vapi_phone_number: purchased.phone_number, vapi_phone_number_id: vapiNumber.id })
    .where(eq(companies.id, dbUser.company_id))

  return NextResponse.json({ success: true, phone_number: purchased.phone_number, provider: 'twilio' })
}
